# Generated by Django 5.2.6 on 2026-02-15 21:08

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR'), ('DEBUG', 'DEBUG')], default='INFO', max_length=10)),
                ('action', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=180)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('focus_tags', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('platform_key', models.SlugField(blank=True, max_length=80, null=True, unique=True)),
                ('platform_vendor', models.CharField(blank=True, default='', max_length=120)),
                ('interop_profile', models.CharField(blank=True, default='', max_length=120)),
                ('member_ds', models.BooleanField(default=False)),
                ('is_dsga', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('connector_endpoint', models.URLField(blank=True, default='')),
                ('certificate_thumbprint', models.CharField(blank=True, default='', max_length=128)),
                ('self_description_jsonld', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('mapping_catalogs_jsonld', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=250)),
                ('password', models.CharField(default='admin', max_length=128)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('availability_preference', models.TextField(blank=True, default='')),
                ('skills', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('is_manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='vms.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(default='INFO', max_length=40)),
                ('actor', models.CharField(default='DEMORG', max_length=40)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_logs', to='vms.volunteer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_esco_uri', models.CharField(default='', max_length=255)),
                ('total_hours', models.IntegerField(default=0)),
                ('certificate_jsonld', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='vms.volunteer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('duration_hours', models.IntegerField(default=1)),
                ('max_attendee_capacity', models.IntegerField(default=0)),
                ('tshirt_size', models.CharField(blank=True, default='', max_length=10)),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
                ('skills', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('isShared', models.BooleanField(default=False)),
                ('isFinished', models.BooleanField(default=False)),
                ('is_federated_cache', models.BooleanField(default=False)),
                ('source_entity_type', models.CharField(blank=True, default='OPPORTUNITY', max_length=40)),
                ('source_local_id', models.CharField(blank=True, default='', max_length=120)),
                ('shared_since', models.DateTimeField(blank=True, null=True)),
                ('ds_endpoint', models.URLField(blank=True, default='')),
                ('ds_asset_id', models.CharField(blank=True, default='', max_length=128)),
                ('canonical_jsonld', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vms.organization')),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='vms.volunteerevent'),
        ),
    ]
