# Generated by Django 5.2.6 on 2025-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteereventregistration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='volunteereventregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='volunteereventregistration',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteertask',
            name='event',
        ),
        migrations.RemoveField(
            model_name='volunteertask',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='volunteertask',
            name='skills_required',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='volunteertaskassignment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='volunteertaskassignment',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='hours_per_week',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_status',
        ),
        migrations.AddField(
            model_name='organization',
            name='is_dsga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='events', to='vms.skill'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='VolunteerEventRegistration',
        ),
        migrations.DeleteModel(
            name='VolunteerTask',
        ),
        migrations.DeleteModel(
            name='VolunteerTaskAssignment',
        ),
    ]
