# Generated by Django 5.2.6 on 2025-09-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_alter_volunteereventregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='start_date',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='vms.volunteerevent'),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='duration_hours',
            field=models.IntegerField(default=1),
        ),
    ]
