# Generated by Django 5.2.6 on 2025-09-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_remove_volunteer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
