# Generated by Django 5.2.6 on 2025-09-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_volunteerevent_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='image',
            field=models.CharField(blank=True, default='default.jpg', max_length=250),
        ),
    ]
