# Generated by Django 5.2.6 on 2025-09-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0005_volunteerevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
