# Generated by Django 5.2.6 on 2025-10-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0008_remove_organization_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='isShared',
            field=models.BooleanField(default=False),
        ),
    ]
