# Generated by Django 5.2.6 on 2025-10-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0009_volunteerevent_isshared'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='ds_asset_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='ds_contract_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='ds_endpoint',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='prioritize_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='shared_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='isShared',
            field=models.BooleanField(default=True),
        ),
    ]
