# Generated by Django 5.2.6 on 2025-10-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0010_volunteerevent_ds_asset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='ds_endpoint',
            field=models.CharField(blank=True, default=''),
        ),
    ]
