# Generated by Django 5.2.6 on 2025-10-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0011_alter_volunteerevent_ds_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='availability_preference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='available_hours_per_week',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
