# Generated by Django 5.2.6 on 2025-10-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0012_volunteer_availability_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='available_hours_per_week',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
