# Generated by Django 5.2.6 on 2026-02-10 10:14

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0013_alter_volunteer_available_hours_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='interop_profile',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='platform_key',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='platform_vendor',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='LocalResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('VOLUNTEER', 'Volunteer'), ('OPPORTUNITY', 'Opportunity'), ('EVENT', 'Event')], max_length=20)),
                ('local_id', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_resources', to='vms.organization')),
            ],
            options={
                'ordering': ['-retrieved_at'],
                'unique_together': {('organization', 'entity_type', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='CanonicalResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('VOLUNTEER', 'Volunteer'), ('OPPORTUNITY', 'Opportunity'), ('EVENT', 'Event')], max_length=20)),
                ('canonical_id', models.CharField(blank=True, default='', max_length=255)),
                ('canonical_jsonld', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_resources', to='vms.organization')),
                ('local_resource', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canonical', to='vms.localresource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
