# Generated by Django 5.2.6 on 2026-02-10 10:36

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0014_organization_interop_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='focus_tags',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
