# Generated by Django 5.2.6 on 2026-02-10 10:56

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0015_organization_country_organization_focus_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerevent',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='skills',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skills_esco',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='canonical_jsonld',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='is_federated_cache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='source_entity_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='source_local_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.DeleteModel(
            name='CanonicalResource',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
