# Generated by Django 5.2.6 on 2026-02-10 10:59

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0016_remove_volunteerevent_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('esco_uri', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='skills_esco',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='canonical_jsonld',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='is_federated_cache',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='source_entity_type',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='source_local_id',
        ),
        migrations.CreateModel(
            name='CanonicalResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('VOLUNTEER', 'Volunteer'), ('OPPORTUNITY', 'Opportunity'), ('EVENT', 'Event')], max_length=20)),
                ('canonical_id', models.CharField(blank=True, default='', max_length=255)),
                ('canonical_jsonld', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_resource', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canonical', to='vms.localresource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_resources', to='vms.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='vms.skill'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='vms.skill'),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='events', to='vms.skill'),
        ),
    ]
