# Generated by Django 5.2.6 on 2026-02-10 11:04

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0017_skill_remove_volunteer_skills_esco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='canonical_jsonld',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
