# Generated by Django 5.2.6 on 2026-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0019_remove_volunteer_canonical_jsonld_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='is_federated_cache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='source_entity_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='source_local_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
