# Generated by Django 5.2.6 on 2026-02-10 13:47

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0020_volunteerevent_is_federated_cache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingCatalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('VOLUNTEER', 'Volunteer'), ('OPPORTUNITY', 'Opportunity')], max_length=20)),
                ('catalog_json', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_catalogs', to='vms.organization')),
            ],
            options={
                'unique_together': {('organization', 'entity_type')},
            },
        ),
    ]
