# Generated by Django 5.2.6 on 2026-02-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0021_mappingcatalog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='volunteerevent',
            constraint=models.UniqueConstraint(fields=('organization', 'is_federated_cache', 'source_entity_type', 'source_local_id'), name='uniq_federated_cache_event'),
        ),
    ]
