# Generated by Django 5.2.6 on 2026-02-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0022_volunteerevent_uniq_federated_cache_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='cross_platform',
            field=models.BooleanField(default=False),
        ),
    ]
