# Generated by Django 5.2.6 on 2026-02-11 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0023_volunteerevent_cross_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canonicalresource',
            name='local_resource',
        ),
        migrations.RemoveField(
            model_name='canonicalresource',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='volunteer',
        ),
        migrations.AlterUniqueTogether(
            name='localresource',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='localresource',
            name='organization',
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
        migrations.AlterUniqueTogether(
            name='mappingcatalog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mappingcatalog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='skills',
        ),
        migrations.RemoveConstraint(
            model_name='volunteerevent',
            name='uniq_federated_cache_event',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='cross_platform',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='ds_contract_id',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='prioritize_local',
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='ds_asset_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='ds_endpoint',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='isShared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.organization'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='source_entity_type',
            field=models.CharField(blank=True, default='OPPORTUNITY', max_length=40),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='source_local_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.DeleteModel(
            name='CanonicalResource',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='LocalResource',
        ),
        migrations.DeleteModel(
            name='MappingCatalog',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
