# Generated by Django 5.2.6 on 2026-02-11 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0024_remove_canonicalresource_local_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vms.organization'),
        ),
    ]
