# Generated by Django 5.2.6 on 2026-02-11 11:33

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0025_alter_volunteerevent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='skills',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
