# Generated by Django 5.2.6 on 2026-02-11 17:22

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0026_volunteerevent_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='skills',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
