# Generated by Django 5.2.6 on 2026-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0027_volunteer_skills_volunteerevent_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='max_attendee_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
