# Generated by Django 5.2.6 on 2026-02-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0028_volunteerevent_max_attendee_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='available_hours_per_week',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
