# Generated by Django 5.2.6 on 2026-02-12 16:30

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0029_remove_volunteer_available_hours_per_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='metadata_json',
        ),
        migrations.AddField(
            model_name='organization',
            name='mapping_catalogs_json',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
