# Generated by Django 5.2.6 on 2026-02-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0030_remove_organization_metadata_json_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='mapping_catalogs_json',
            new_name='mapping_catalogs_jsonld',
        ),
    ]
