# Generated by Django 5.2.6 on 2026-02-12 16:38

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0031_rename_mapping_catalogs_json_organization_mapping_catalogs_jsonld'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='organization',
            name='self_description_jsonld',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
