# Generated by Django 5.2.6 on 2026-02-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0032_organization_metadata_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='metadata_json',
        ),
    ]
