# Generated by Django 5.2.6 on 2026-02-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0033_remove_organization_metadata_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='tshirt_size',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
