# Generated by Django 5.2.6 on 2026-02-14 18:08

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0034_volunteerevent_tshirt_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_esco_uri', models.CharField(default='', max_length=255)),
                ('total_hours', models.IntegerField(default=0)),
                ('certificate_jsonld', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='vms.volunteer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='INFO', max_length=80)),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_logs', to='vms.volunteer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
