# Generated by Django 5.2.6 on 2026-02-14 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0035_certificateissue_certificatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR'), ('DEBUG', 'DEBUG')], default='INFO', max_length=10)),
                ('action', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='certificatelog',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='certificatelog',
            name='type',
        ),
        migrations.AddField(
            model_name='certificatelog',
            name='actor',
            field=models.CharField(default='DEMORG', max_length=40),
        ),
        migrations.AddField(
            model_name='certificatelog',
            name='endpoint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificatelog',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='certificatelog',
            name='step',
            field=models.CharField(default='INFO', max_length=40),
        ),
        migrations.AlterField(
            model_name='certificatelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
